export const heritageSites = [
    {
        id: 1,
        name: "Bugonga Church",
        city: "Entebbe",
        description: "One of the oldest permanent Catholic churches in Uganda, marking the spot where the first Catholic missionaries camped in 1899.",
        location: { latitude: 0.0517, longitude: 32.4637 },
        images: [require("./assets/bugonga_church.jpg"), require("./assets/bugonga_church.jpg")],
      },
  {
        id: 2,
        name: "Chadwick Namatte Primary School",
        city: "Entebbe",
        description: "Founded in 1910 as Entebbe Central School, it is one of the earliest schools established for Africans.",
        location: { latitude: 0.0521, longitude: 32.4603 },
        images: [require("./assets/chadwick_school.jpg"), require("./assets/chadwick_school.jpg")],
      },
  {
        id: 3,
        name: "Entebbe Botanical Gardens",
        city: "Entebbe",
        description: "Established in 1898, these are the oldest botanical gardens in Uganda and were used as a filming location for 'Tarzan’s Hidden Jungle' in 1954.",
        location: { latitude: 0.0583, longitude: 32.4825 },
       // images: [require("./assets/botanical_gardens.png"), require("./assets/botanical_gardens.png")],
      },
  {
        id: 4,
        name: "Entebbe Golf Club Club house",
        city: "Entebbe",
        description: "Founded in 1913, this clubhouse was built for British colonial administrators and expatriates.",
        location: { latitude: 0.0512, longitude: 32.4645 },
        //images: [require("./assets/golf_club.png"), require("./assets/golf_club.png")],
      },
  {
        id: 5,
        name: "Entebbe Old Airport Tower",
        city: "Entebbe",
        description: "Built in 1952, this tower is known for the 1976 hostage rescue operation by Israeli forces.",
        location: { latitude: 0.0423, longitude: 32.4432 },
        //images: [require("./assets/old_airport_tower.png"), require("./assets/old_airport_tower.png")],
      },
  {
        id: 6,
        name: "Entebbe Post Office",
        city: "Entebbe",
        description: "One of Uganda’s oldest post offices, dating back to the early 1900s.",
        location: { latitude: 0.0508, longitude: 32.4621 },
        //images: [require("./assets/post_office.png"), require("./assets/post_office.png")],
      },
  {
        id: 7,
        name: "Independence Tree",
        city: "Entebbe",
        description: "A historic tree used as a rallying point for nationalist leaders before Uganda's independence in 1962.",
        location: { latitude: 0.0495, longitude: 32.4598 },
        images: [require("./assets/independence_tree.jpg"), require("./assets/independence_tree.jpg")],
      },
  {
        id: 8,
        name: "Lake Victoria Hotel",
        city: "Entebbe",
        description: "A historic hotel built in 1948, famous for hosting Queen Elizabeth II in 1958.",
        location: { latitude: 0.0511, longitude: 32.4629 },
        //images: [require("./assets/lake_victoria_hotel.png"), require("./assets/lake_victoria_hotel.png")],
      },
  {
        id: 9,
        name: "Ministry of Agriculture Building",
        city: "Entebbe",
        description: "Built in 1927, this colonial-era building still houses the Ministry of Agriculture.",
        location: { latitude: 0.0529, longitude: 32.4617 },
        images: [require("./assets/agriculture_building.jpg"), require("./assets/agriculture_building.jpg")],
      },
  {
        id: 10,
        name: "The Secretariat",
        city: "Entebbe",
        description: "A grand colonial administrative building from the 1910s, serving as the Secretariat to the Governor’s Office.",
        location: { latitude: 0.0532, longitude: 32.4609 },
        images: [require("./assets/secretariat.jpg"), require("./assets/secretariat.jpg")],
      },
  {
        id: 11,
        name: "Entebe Za Mugula",
        city: "Entebbe",
        description: "A sacred site where Chief Mugula Bukulubwawadda presided over judicial cases in the 19th century.",
        location: { latitude: 0.0541, longitude: 32.4583 },
        images: [require("./assets/entebe_za_mugula.jpg"), require("./assets/entebe_za_mugula.jpg")],
      },
  {
        id: 12,
        name: "St John’s Church",
        city: "Entebbe",
        description: "Built in 1939, this Anglican church has served Entebbe’s community for over 80 years.",
        location: { latitude: 0.0487, longitude: 32.4635 },
        images: [require("./assets/st_johnse_cathedral.jpg"), require("./assets/st_johnse_cathedral.jpg")],
      },
  {
        id: 13,
        name: "Stanbic Bank Building",
        city: "Entebbe",
        description: "A historic bank built around 1950, formerly housing Uganda Commercial Bank.",
        location: { latitude: 0.0479, longitude: 32.4612 },
        images: [require("./assets/stanbic_bank.jpg"), require("./assets/stanbic_bank.jpg")],
      },
  {
        id: 14,
        name: "Maps and Surveys Building",
        city: "Entebbe",
        description: "Built in 1930, this building served as Uganda’s headquarters for maps and surveys.",
        location: { latitude: 0.0502, longitude: 32.4640 },
        //images: [require("./assets/maps_surveys.png"), require("./assets/maps_surveys.png")],
      },
    // Entebbe building ending here
    // Begining of Kampala
  {
        id: 15,
        name: "Kabaka’s Lake",
        city: "Kampala",
        description: "Possibly the largest hand-dug lake in Africa, excavated in 1886 on Kabaka Mwanga II’s command as part of an escape route to Lake Victoria.",
        location: { latitude: 0.2956, longitude: 32.5634 },
        images: [require("./assets/kabaka_lake.jpg"), require("./assets/kabaka_lake.jpg")],
      },
  {
        id: 16,
        name: "Basiima House",
        city: "Kampala",
        description: "Built between 1902-1905, one of Uganda's first two-storey buildings with a mix of British, Arab, and Ugandan architectural styles.",
        location: { latitude: 0.3189, longitude: 32.5820 },
        images: [require("./assets/Basiima.jpg"), require("./assets/Basiima.jpg")],
      },
  {
        id: 17,
        name: "Bulange",
        city: "Kampala",
        description: "Built in 1958, this is the administrative seat of the Buganda Kingdom, inspired by the Stormont building in Belfast, Northern Ireland.",
        location: { latitude: 0.3121, longitude: 32.5745 },
        images: [require("./assets/bulange.jpg"), require("./assets/bulange.jpg")],
      },
  {
        id: 18,
        name: "Twekobe",
        city: "Kampala",
        description: "The official residence of the Kabaka of Buganda, built between 1922-1933 within the Lubiri palace grounds.",
        location: { latitude: 0.3104, longitude: 32.5689 },
        images: [require("./assets/Twekobe.jpg"), require("./assets/Twekobe.jpg")],
      },
  {
        id: 19,
        name: "Kasubi Tombs",
        city: "Kampala",
        description: "A UNESCO World Heritage Site and burial site of four Buganda Kabakas, originally Kabaka Muteesa I’s palace (1880-1884).",
        location: { latitude: 0.3284, longitude: 32.5578 },
        images: [require("./assets/kasubi_tombs.jpg"), require("./assets/kasubi_tombs.jpg")],
      },
  {
        id: 20,
        name: "Makerere Main Building",
        city: "Kampala",
        description: "The administrative building for East Africa’s oldest university (established 1922), built between 1939-1941.",
        location: { latitude: 0.3322, longitude: 32.5700 },
        images: [require("./assets/makerere_main_building.jpg"), require("./assets/makerere_main_building.jpg")],
      },
  {
        id: 21,
        name: "Uganda Museum",
        city: "Kampala",
        description: "East Africa’s oldest museum, established in 1901 and moved to its current Modernist building in 1954.",
        location: { latitude: 0.3350, longitude: 32.5825 },
        images: [require("./assets/Uganda_museum.jpg"), require("./assets/Uganda_museum.jpg")],
      },
      {
        id: 22,
        name: "St. Mary’s Cathedral Lubaga",
        city: "Kampala",
        description: "Constructed between 1914-1925 by the White Fathers, this cathedral sits on a hill granted to the Catholic Church in 1888.",
        location: { latitude: 0.3115, longitude: 32.5682 },
        images: [require("./assets/st_marys_cathedral.jpg"), require("./assets/st_marys_cathedral.jpg")],
      },
  {
        id: 23,
        name: "Parliament of Uganda",
        city: "Kampala",
        description: "Built in 1958 to symbolize Uganda’s transition to independence, featuring a wooden mural showcasing Uganda’s flora and fauna.",
        location: { latitude: 0.3154, longitude: 32.5828 },
        images: [require("./assets/Parliament.jpg"), require("./assets/Parliament.jpg")],
      },
  {
        id: 24,
        name: "Independence Monument",
        city: "Kampala",
        description: "Designed by Gregory Magoba, this 1962 sculpture celebrates Uganda’s independence from British rule.",
        location: { latitude: 0.3170, longitude: 32.5842 },
        images: [require("./assets/independence_monument.jpg"), require("./assets/independence_monument.jpg")],
      },
  {
        id: 25,
        name: "Buganda Road Primary School",
        city: "Kampala",
        description: "Founded in 1933 by Norman Godinho, initially an Indian-only school, later opened to indigenous Ugandans.",
        location: { latitude: 0.3165, longitude: 32.5789 },
        images: [require("./assets/buganda_road_school.jpg"), require("./assets/buganda_road_school.jpg")],
      },
  {
        id: 26,
        name: "Kibuli Mosque",
        city: "Kampala",
        description: "Built between 1941-1951 on land donated by Prince Nuhu Mbogo, featuring the first qibla in Uganda.",
        location: { latitude: 0.3199, longitude: 32.5972 },
        images: [require("./assets/kibuli_mosque.jpg"), require("./assets/kibuli_mosque.jpg")],
      },
  {
        id: 27,
        name: "Nakasero Market",
        city: "Kampala",
        description: "Constructed in 1927 by colonial administrators, Uganda’s oldest permanent market structure.",
        location: { latitude: 0.3183, longitude: 32.5894 },
        images: [require("./assets/nakasero_market.jpg"), require("./assets/nakasero_market.jpg")],
      },
  {
        id: 28,
        name: "Kabaka Muteesa I Royal Mosque",
        city: "Kampala",
        description: "Originally built in 1856 with bamboo and earth, later reconstructed in 1967.",
        location: { latitude: 0.3167, longitude: 32.5751 },
        //images: [require("./assets/kabaka_mosque.jpg"), require("./assets/kabaka_mosque.jpg")],
      },
  {
        id: 29,
        name: "Swaminarayan Hindu Temple",
        city: "Kampala",
        description: "Built in 1960, the largest Swaminarayan temple in East Africa, serving the Gujarati community.",
        location: { latitude: 0.3204, longitude: 32.5818 },
        images: [require("./assets/swaminarayan_temple.jpg"), require("./assets/swaminarayan_temple.jpg")],
      },

      {
            id: 30,
            name: "All Saints’ Cathedral",
            city: "Kampala",
            description: "Founded in 1912 as a chaplaincy for a European-only hospital in Nakasero, later became the seat of the Archbishop of the Church of Uganda.",
            location: { latitude: 0.3195, longitude: 32.5890 },
            images: [require("./assets/All_Saints_Cathedral.jpg"), require("./assets/All_Saints_Cathedral.jpg")],
          },
      {
            id: 31,
            name: "Watoto Church (Former Norman Cinema)",
            city: "Kampala",
            description: "Originally built in the early 1950s as Norman Cinema, later became a church in the 1980s.",
            location: { latitude: 0.3178, longitude: 32.5825 },
            images: [require("./assets/watoto_church.jpg"), require("./assets/watoto_church.jpg")],
          },
      {
            id: 32,
            name: "St Paul’s Cathedral Namirembe",
            city: "Kampala",
            description: "Constructed between 1915-1919, the seat of the Anglican Church in Uganda, known for its neo-gothic and Byzantine features.",
            location: { latitude: 0.3128, longitude: 32.5746 },
            images: [require("./assets/namirembe_cathedral.jpg"), require("./assets/namirembe_cathedral.jpg")],
          },
      {
            id: 33,
            name: "Uganda Railway Station",
            city: "Kampala",
            description: "Built in 1940 after the Uganda railway reached Kampala from Mombasa in 1931, contains many original fittings.",
            location: { latitude: 0.3173, longitude: 32.5831 },
            images: [require("./assets/railway_station.jpg"), require("./assets/railway_station.jpg")],
          },
      {
            id: 34,
            name: "Fort Jesus Building, St. Peter’s School Nsambya",
            city: "Kampala",
            description: "Built between 1895-1907, the first mission house of the Mill Hill Missionaries, later replaced by St. Peter’s Church in 1951.",
            location: { latitude: 0.3082, longitude: 32.5871 },
            images: [require("./assets/Fort-Jesus-Building,-St-Peters-School-Nsambya.jpg"), require("./assets/Fort-Jesus-Building,-St-Peters-School-Nsambya.jpg")],
          },
      {
            id: 35,
            name: "Bank of Uganda",
            city: "Kampala",
            description: "Construction started in 1967, opened in 1969, marking the establishment of Uganda’s first permanent central bank premises.",
            location: { latitude: 0.3176, longitude: 32.5849 },
            images: [require("./assets/Bank_of_Uganda.jpg"), require("./assets/Bank_of_Uganda.jpg")],
          },
          {
            id: 36,
            name: "New Mulago Hospital buildings",
            city: "Kampala",
            description: "Completed in 1962, marking Uganda’s independence, regarded as one of the region’s leading teaching hospitals.",
            location: { latitude: 0.3418, longitude: 32.5824 },
            images: [require("./assets/new_mulago.jpg"), require("./assets/new_mulago.jpg")],
          },
      {
            id: 37,
            name: "Uganda National Theatre",
            city: "Kampala",
            description: "Built in 1956 to promote Ugandan expressive art in the run-up to independence.",
            location: { latitude: 0.3171, longitude: 32.5847 },
            images: [require("./assets/national_theatre.jpg"), require("./assets/national_theatre.jpg")],
          },
      {
            id: 38,
            name: "Patidar Samaj Trust Building",
            city: "Kampala",
            description: "Built in 1935 as a cultural and religious center for the Patel and Gujarati communities, now houses the Uganda National Library.",
            location: { latitude: 0.3192, longitude: 32.5855 },
            images: [require("./assets/patidar_samaj.jpg"), require("./assets/patidar_samaj.jpg")],
          },
      {
            id: 39,
            name: "The Baha’i House of Worship",
            city: "Kampala",
            description: "Built in 1958, the Mother Temple for Africa, an architectural landmark with extensive gardens.",
            location: { latitude: 0.3648, longitude: 32.5969 },
            images: [require("./assets/bahai_temple.jpg"), require("./assets/bahai_temple.jpg")],
          },
      {
            id: 40,
            name: "St. Peter’s Nsambya Church",
            city: "Kampala",
            description: "Built in 1951 to replace the original mission house of the Mill Hill Missionaries, established in 1895.",
            location: { latitude: 0.3085, longitude: 32.5862 },
           // images: [require("./assets/st_peters_nsambya.png"), require("./assets/st_peters_nsambya.png")],
          },
      {
            id: 41,
            name: "Vector Control Unit",
            city: "Kampala",
            description: "Built in 1926, originally the Malaria Control Unit, playing a crucial role in early colonial health services.",
            location: { latitude: 0.3207, longitude: 32.5834 },
            images: [require("./assets/vector_control.jpg"), require("./assets/vector_control.jpg")],
          },
      {
            id: 42,
            name: "Luke and Katherine Wards, Mengo Hospital",
            city: "Kampala",
            description: "Built in 1904, part of Uganda’s first hospital established by Dr. Albert Cook.",
            location: { latitude: 0.3131, longitude: 32.5736 },
            images: [require("./assets/mengo_hospital.jpg"), require("./assets/mengo_hospital.jpg")],
          },
      {
            id: 43,
            name: "Government House",
            city: "Kampala",
            description: "Built in the 1920s, historically housed colonial governors before becoming part of State House.",
            location: { latitude: 0.3148, longitude: 32.5830 },
            //images: [require("./assets/government_house.png"), require("./assets/government_house.png")],
          },
      {
            id: 44,
            name: "Makindye Sub-County (Gombolola) Building",
            city: "Kampala",
            description: "Built in 1930, an example of Buganda Kingdom’s administrative structures used until 1966.",
            location: { latitude: 0.3089, longitude: 32.5732 },
            images: [require("./assets/makindye_building.jpg"), require("./assets/makindye_building.jpg")],
          },
      {
            id: 45,
            name: "Old Mitchell Hall, Makerere University",
            city: "Kampala",
            description: "Built in 1922, originally named after Sir Phillip Mitchell, one of the first student residences at Makerere University.",
            location: { latitude: 0.3324, longitude: 32.5709 },
            images: [require("./assets/mitchell_hall.jpg"), require("./assets/mitchell_hall.jpg")],
          },
      {
            id: 46,
            name: "Nateete Martyrs’ Church",
            city: "Kampala",
            description: "Built in 1906 on the site where Alexander Mackay taught the first Anglican converts in Uganda.",
            location: { latitude: 0.3065, longitude: 32.5543 },
            images: [require("./assets/nateete_church.jpg"), require("./assets/nateete_church.jpg")],
          },
      {
            id: 47,
            name: "Namasole Maasombira’s Palace",
            city: "Kampala",
            description: "The palace of Evelyn Kulabako Maasombira, the Queen Mother of Kabaka Daudi Chwa II.",
            location: { latitude: 0.3123, longitude: 32.5664 },
            images: [require("./assets/namasole_palace.jpg"), require("./assets/namasole_palace.jpg")],
          },
      {
            id: 48,
            name: "Treasury Annex Building",
            city: "Kampala",
            description: "Constructed in 1935, used for central government financial administration.",
            location: { latitude: 0.3168, longitude: 32.5841 },
            images: [require("./assets/treasury_annex.png"), require("./assets/treasury_annex.png")],
          },
      {
            id: 49,
            name: "Mulago School of Nursing",
            city: "Kampala",
            description: "Built in 1953, a leading institution for nursing education in Uganda.",
            location: { latitude: 0.3410, longitude: 32.5828 },
            //images: [require("./assets/mulago_nursing.png"), require("./assets/mulago_nursing.png")],
          },
      {
            id: 50,
            name: "Old Kampala Hill",
            city: "Kampala",
            description: "The original site of the British colonial administration before they moved to Nakasero.",
            location: { latitude: 0.3156, longitude: 32.5762 },
            //images: [require("./assets/old_kampala.png"), require("./assets/old_kampala.png")],
          },
          {
            id: 106,
            name: "Shri Dharmasthala Manjunatheshwara (SDM) Temple",
            city: "Kampala",
            description: "Coming soon",
            location: { latitude: 0.3156, longitude: 32.5762 },
            images: [require("./assets/Shri-Dharmasthala-Manjunatheshwara-(SDM)-Temple.jpg"), require("./assets/Shri-Dharmasthala-Manjunatheshwara-(SDM)-Temple.jpg")],
          },
      {
            id: 51,
            name: "Plot 44, Rashid Khamis Road",
            city: "Kampala",
            description: "A unique example of 1920s’ Art Deco architecture in Kampala, originally built as a petrol station.",
            location: { latitude: 0.3182, longitude: 32.5790 },
            images: [require("./assets/rashid_khamis.jpg"), require("./assets/rashid_khamis.jpg")],
          },
      {
            id: 52,
            name: "Butikkiro House",
            city: "Kampala",
            description: "The official residence of the Katikkiro (Prime Minister) of Buganda, occupied by five Prime Ministers before being taken over by the army in 1966.",
            location: { latitude: 0.3137, longitude: 32.5715 },
            images: [require("./assets/Butikkiro.jpg"), require("./assets/Butikkiro.jpg")],
          },
      {
            id: 53,
            name: "Bulange Gardens",
            city: "Kampala",
            description: "The gardens surrounding Bulange, the seat of the Buganda Kingdom, featuring clan totem symbols and historical monuments.",
            location: { latitude: 0.3125, longitude: 32.5732 },
            //images: [require("./assets/bulange_gardens.png"), require("./assets/bulange_gardens.png")],
          },
      {
            id: 54,
            name: "Treasury Building",
            city: "Kampala",
            description: "Built in 1930, this colonial-era structure housed the financial administration of the British Protectorate government.",
            location: { latitude: 0.3162, longitude: 32.5812 },
            images: [require("./assets/treasury_annex.png"), require("./assets/treasury_annex.png")],
          },
      {
            id: 55,
            name: "Prince Nuhu Mbogo’s Tomb",
            city: "Kampala",
            description: "The burial site of Prince Nuhu Mbogo (1835-1921), a significant leader in Uganda’s Islamic history.",
            location: { latitude: 0.3120, longitude: 32.5753 },
            images: [require("./assets/mbogo_tomb.jpg"), require("./assets/mbogo_tomb.jpg")],
          },
      {
            id: 56,
            name: "Old Mulago Hospital buildings",
            city: "Kampala",
            description: "Established between 1927-1937 by Albert Cook, some of the oldest surviving hospital structures in Uganda.",
            location: { latitude: 0.3403, longitude: 32.5829 },
            images: [require("./assets/old_mulago.jpg"), require("./assets/old_mulago.jpg")],
          },
      {
            id: 57,
            name: "Kampala Club",
            city: "Kampala",
            description: "Opened in 1911 as a private members’ club for colonial officers, became open to Ugandans in the 1960s.",
            location: { latitude: 0.3190, longitude: 32.5841 },
            images: [require("./assets/kampala_club.jpg"), require("./assets/kampala_club.jpg")],
          },
      {
            id: 58,
            name: "Makerere University Mitchell Hall",
            city: "Kampala",
            description: "Built in 1922, one of the first student residences at Makerere University, originally named after Sir Phillip Mitchell.",
            location: { latitude: 0.3310, longitude: 32.5708 },
            images: [require("./assets/mitchell_hall.jpg"), require("./assets/mitchell_hall.jpg")],
          },
      {
            id: 59,
            name: "Margaret Trowell School of Industrial and Fine Arts",
            city: "Kampala",
            description: "Founded in 1922, this school pioneered formal art education in Uganda.",
            location: { latitude: 0.3308, longitude: 32.5695 },
            images: [require("./assets/trowell_school.jpg"), require("./assets/trowell_school.jpg")],
          },
      {
            id: 60,
            name: "Ebenezer House",
            city: "Kampala",
            description: "Built in 1937, the last building of this period in central Kampala, occupied by the Uganda Bookshop since 1977.",
            location: { latitude: 0.3187, longitude: 32.5843 },
            images: [require("./assets/Ebenezer_house.jpg"), require("./assets/Ebenezer_house.jpg")],
          },
      {
            id: 61,
            name: "Government National Analytical Laboratory",
            city: "Kampala",
            description: "Built between 1925-1927, this facility provided critical public health analysis during the early colonial period.",
            location: { latitude: 0.3164, longitude: 32.5832 },
            images: [require("./assets/analytical_lab.png"), require("./assets/analytical_lab.png")],
          },
      {
            id: 62,
            name: "Old Kampala Police Station",
            city: "Kampala",
            description: "Established in 1929, the only surviving colonial police station from the early protectorate era.",
            location: { latitude: 0.3180, longitude: 32.5756 },
            images: [require("./assets/kampala_police.jpg"), require("./assets/kampala_police.jpg")],
          },

          {
                id: 63,
                name: "High Court Building",
                city: "Kampala",
                description: "Built in 1930, one of the last remaining examples of neo-classical colonial architecture in Kampala.",
                location: { latitude: 0.3159, longitude: 32.5840 },
                images: [require("./assets/high_court.jpg"), require("./assets/high_court.jpg")],
              },
          {
                id: 64,
                name: "Mengo Primary School",
                city: "Kampala",
                description: "Established in 1904 as Kayanja Elementary School, home to the oldest surviving formal education building in Uganda.",
                location: { latitude: 0.3142, longitude: 32.5738 },
                images: [require("./assets/mengo_primary.jpg"), require("./assets/mengo_primary.jpg")],
              },
          {
                id: 65,
                name: "Mayor’s Parlour",
                city: "Kampala",
                description: "Opened in 1949 as the Old Hall for Kampala City Council, marking the time Kampala became a city.",
                location: { latitude: 0.3185, longitude: 32.5849 },
                images: [require("./assets/mayors_parlour.jpg"), require("./assets/mayors_parlour.jpg")],
              },
          {
                id: 66,
                name: "Nakasero Hindu Temple",
                city: "Kampala",
                description: "Built in 1954, a masterpiece of Indian masonry with intricate stonework, a significant religious site for Kampala’s Hindu community.",
                location: { latitude: 0.3172, longitude: 32.5860 },
                images: [require("./assets/nakasero_hindu_temple.jpg"), require("./assets/nakasero_hindu_temple.jpg")],
              },
          {
                id: 67,
                name: "Prince Nuhu Mbogo’s Tomb",
                city: "Kampala",
                description: "Final resting place of Prince Nuhu Mbogo, a key figure in Uganda’s Islamic history, exiled by the British in 1893.",
                location: { latitude: 0.3127, longitude: 32.5712 },
                images: [require("./assets/mbogo_tomb.jpg"), require("./assets/mbogo_tomb.jpg")],
              },

          
      // Add more sites as needed
      // fort portal
      {
            id: 68,
            name: "Lake Kigere",
            city: "Fort Portal",
            description: "A spiritual site associated with the Batembuzi dynasty, featuring a large footprint believed to belong to one of its last kings.",
            location: { latitude: 0.6715, longitude: 30.2754 },
            images: [require("./assets/lake_kigere.jpg"), require("./assets/lake_kigere.jpg")],
          },
      {
            id: 69,
            name: "Amabere ga Nyinamwiru Cave and Stalactites",
            city: "Fort Portal",
            description: "A legendary site with breast-like stalactites, named after Nyinamwiru, daughter of King Bukuku of the Batembuzi dynasty.",
            location: { latitude: 0.6698, longitude: 30.2643 },
            //images: [require("./assets/amabere_cave.png"), require("./assets/amabere_cave.png")],
          },
      {
            id: 70,
            name: "Ibaale – The Rock",
            city: "Fort Portal",
            description: "An ancestral place of worship with footprints and other marks, believed to be signs of gods passing through the area.",
            location: { latitude: 0.6753, longitude: 30.2587 },
            images: [require("./assets/ibaale_rock.jpg"), require("./assets/ibaale_rock.jpg")],
          },
      {
            id: 71,
            name: "Fort Gerry and Tooro Golf Club",
            city: "Fort Portal",
            description: "Built in 1893 by Lord Lugard, this fort defended Tooro against Bunyoro’s troops. Its defensive ditches can still be seen around the golf club.",
            location: { latitude: 0.6642, longitude: 30.2750 },
           // images: [require("./assets/fort_gerry.png"), require("./assets/fort_gerry.png")],
          },
      {
            id: 72,
            name: "Kyebambe Girls’ School",
            city: "Fort Portal",
            description: "Founded in 1910 and named after King Kasagama Kyebambe III, with one of its first buildings still standing over 100 years later.",
            location: { latitude: 0.6721, longitude: 30.2805 },
            //images: [require("./assets/kyebambe_school.png"), require("./assets/kyebambe_school.png")],
          },
      {
            id: 73,
            name: "The Karuzika – The Royal Palace",
            city: "Fort Portal",
            description: "First built in 1910 and rebuilt in 1964, this palace sits atop Kabarole Hill and has been a symbol of the Tooro Kingdom.",
            location: { latitude: 0.6680, longitude: 30.2736 },
            images: [require("./assets/karuzika_palace.jpg"), require("./assets/karuzika_palaces.jpg")],
          },
      {
            id: 74,
            name: "Kabarole Hospital",
            city: "Fort Portal",
            description: "Established in 1903 by the Church Missionary Society, it is Uganda’s second-oldest Western-style medical facility.",
            location: { latitude: 0.6702, longitude: 30.2769 },
            images: [require("./assets/kabarole_hospital.jpg"), require("./assets/kabarole1_hospital.jpg")],
          },
      {
            id: 75,
            name: "Karambi Tombs",
            city: "Fort Portal",
            description: "The burial site of Tooro Kings, including Kasagama Kyebambe III, George Kamurasi Rukidi III, and Olimi Kaboyo VII.",
            location: { latitude: 0.6651, longitude: 30.2732 },
            images: [require("./assets/karambi_tombs.jpg"), require("./assets/karambi_tombs.jpg")],
          },
      {
            id: 76,
            name: "Rwengoma Palace",
            city: "Fort Portal",
            description: "Built in 1909 by King Kyebambe for his mother, Victoria Kahinju. Later occupied by his son, a fine example of early colonial architecture.",
            location: { latitude: 0.6684, longitude: 30.2781 },
            images: [require("./assets/rwengoma_palace.jpg"), require("./assets/rwengoma_palaces.jpg")],
          },
      {
            id: 77,
            name: "Mucwa Chambers – Tooro’s Parliament",
            city: "Fort Portal",
            description: "Built in 1964 as the administrative headquarters of the Tooro Kingdom, reflecting the power of the Kingdom at the time.",
            location: { latitude: 0.6675, longitude: 30.2720 },
            images: [require("./assets/mucwa_chambers.jpg"), require("./assets/mucwa_chambers.jpg")],
          },

          {
            id: 78,
            name: "Kitumba Mosque",
            city: "Fort Portal",
            description: "The first mosque in the Kabarole region built with durable materials in 1922, replacing an earlier grass-thatched structure from the 1890s.",
            location: { latitude: 0.6658, longitude: 30.2785 },
            images: [require("./assets/kitumba_mosque.jpg"), require("./assets/kitumba_mosque1.jpg")],
          },
      {
            id: 79,
            name: "St John’s Cathedral",
            city: "Fort Portal",
            description: "Constructed between 1937-1939 under the supervision of Aberi Kakomya, a key figure in translating the Bible into Runyoro/Rutooro.",
            location: { latitude: 0.6672, longitude: 30.2740 },
            images: [require("./assets/st_johns_cathedral.jpg"), require("./assets/st_johns_cathedrals.jpg")],
          },
      {
            id: 80,
            name: "Aga Khan Mosque",
            city: "Fort Portal",
            description: "Opened in 1960 for the Ismaili community; later opened to all Muslims in Amin’s era before being returned to the Ismaili community in 2001.",
            location: { latitude: 0.6665, longitude: 30.2775 },
            images: [require("./assets/aga_khan_mosque.jpg"), require("./assets/aga_khan_mosque11.jpg")],
          },
      {
            id: 81,
            name: "Mother Eucalyptus Trees",
            city: "Fort Portal",
            description: "Planted in 1925 by the Duke and Duchess of York (later King George VI and Queen Mother) during their visit to Uganda.",
            location: { latitude: 0.6683, longitude: 30.2762 },
            images: [require("./assets/mother_eucalyptus.jpg"), require("./assets/mother_eucalyptus1.jpg")],
          },
      {
            id: 82,
            name: "St Leo’s College",
            city: "Fort Portal",
            description: "Founded in the 1920s, it was the first Catholic secondary school in the region and moved to its current location in the 1960s.",
            location: { latitude: 0.6709, longitude: 30.2758 },
            images: [require("./assets/st_leos_college.jpg"), require("./assets/st_leos_college1.jpg")],
          },
      {
            id: 83,
            name: "Virika Cathedral",
            city: "Fort Portal",
            description: "Destroyed in a 1966 earthquake and rebuilt in 1967, it sits on the site of the first Catholic presence in Fort Portal.",
            location: { latitude: 0.6696, longitude: 30.2791 },
            images: [require("./assets/virika_cathedral.jpg"), require("./assets/virika_cathedral1.jpg")],
          },
      {
            id: 84,
            name: "Nyakasura School",
            city: "Fort Portal",
            description: "Established in 1926 by Scottish officer Ernest Calwell, it is known for its kilts as part of the school uniform and for having Uganda’s first cricket pitch.",
            location: { latitude: 0.6715, longitude: 30.2728 },
            images: [require("./assets/nyakasura_school.jpg"), require("./assets/nyakasura_school1.jpg")],
          },
      {
            id: 85,
            name: "Canon Apollo College Chapel",
            city: "Fort Portal",
            description: "Built around 1961 with volcanic rock, this striking chapel is part of the historical Canon Apollo Teachers' College.",
            location: { latitude: 0.6723, longitude: 30.2767 },
            images: [require("./assets/canon_apollo_chapel1.jpg"), require("./assets/canon_apollo_chapel.jpg")],
          },
      {
            id: 86,
            name: "The Library",
            city: "Fort Portal",
            description: "Originally built in 1952 as Fort Portal’s first Ismaili mosque before being converted into a public library in 1963.",
            location: { latitude: 0.6680, longitude: 30.2755 },
            images: [require("./assets/fort_portal_library.jpg"), require("./assets/fort_portal_library.jpg")],
          },
      {
            id: 87,
            name: "Shops along Lugard Road",
            city: "Fort Portal",
            description: "Dating from the 1920s, these shops represent the early commercial influence of the Asian community in Fort Portal.",
            location: { latitude: 0.6686, longitude: 30.2761 },
            images: [require("./assets/lugard_road_shops.jpg"), require("./assets/lugard_road_shops1.jpg")],
          },
      {
            id: 88,
            name: "The Bookshop",
            city: "Fort Portal",
            description: "Built around 1958, featuring unique bow windows, this structure remains one of the town’s historical commercial buildings.",
            location: { latitude: 0.6689, longitude: 30.2757 },
            images: [require("./assets/fort_portal_bookshop.jpg"), require("./assets/fort_portal_bookshop.jpg")],
          },
      {
            id: 89,
            name: "The Banks",
            city: "Fort Portal",
            description: "The first bank in Fort Portal opened in 1909, marking the town’s growing economic activity during the colonial period.",
            location: { latitude: 0.6687, longitude: 30.2759 },
            images: [require("./assets/fort_portal_banks.jpg"), require("./assets/fort_portal_banks.jpg")],
          },
      {
            id: 90,
            name: "Asian Housing on Mugurusi Road",
            city: "Fort Portal",
            description: "Built between 1940-1960 as a segregated Asian residential area during the colonial period, now part of the town’s diverse heritage.",
            location: { latitude: 0.6693, longitude: 30.2763 },
            images: [require("./assets/mugurusi_road_housing.jpg"), require("./assets/mugurusi_road_housing.jpg")],
          },
      {
            id: 91,
            name: "Local Government Offices",
            city: "Fort Portal",
            description: "Erected in 1952 as the administrative center for Uganda’s Western Region, later damaged by an earthquake but still in use.",
            location: { latitude: 0.6671, longitude: 30.2749 },
            images: [require("./assets/local_government_offices.jpg"), require("./assets/local_government_offices1.jpg")],
          },
      {
            id: 92,
            name: "Akaswa Mount",
            city: "Fort Portal",
            description: "A man-made mound where the fire symbolizing the continuity of the Tooro dynasty was buried during King Kyebambe’s reign.",
            location: { latitude: 0.6712, longitude: 30.2735 },
            images: [require("./assets/akaswa_mount.png"), require("./assets/akaswa_mount.png")],
          },
          {
            id: 93,
            name: "Albert Cook House",
            city: "Kampala",
            description: "A man-made mound where the fire symbolizing the continuity of the Tooro dynasty was buried during King Kyebambe’s reign.",
            location: { latitude: 0.6712, longitude: 30.2735 },
            images: [require("./assets/Albert-Cook-House.jpg"), require("./assets/Albert-Cook-House.jpg")],
          },
      {
          id: 94,
          name: "Amin's Dungeon",
          city: "Kampala",
          description: "A man-made mound where the fire symbolizing the continuity of the Tooro dynasty was buried during King Kyebambe’s reign.",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/Amin's-Dungeon.jpg"), require("./assets/Amin's-Dungeon.jpg")],
        },
        {
          id: 95,
          name: "Busega Martyrs'Memorial",
          city: "Kampala",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/Busega-Martyrs-Memorial.jpg"), require("./assets/Busega-Martyrs-Memorial.jpg")],
        },
      {
          id: 96,
          name: "Coffee Marketing Board",
          city: "Kampala",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/Coffee-Marketing-Board.jpg"), require("./assets/Coffee-Marketing-Board.jpg")],
        },
        {
          id: 97,
          name: "District Offices",
          city: "Kampala",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/District-Offices.jpg"), require("./assets/District-Offices.jpg")],
        },
        {
          id: 98,
          name: "Emin Pasha Hotel",
          city: "Kampala",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/Emin-Pasha-Hotel.jpg"), require("./assets/Emin-Pasha-Hotel.jpg")],
        },
        {
          id: 99,
          name: "Entebbe",
          city: "Entebbe",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/Entebbe.jpg"), require("./assets/Entebbe.jpg")],
        },
        {
          id: 100,
          name: "Hamu Mukasa Building",
          city: "Entebbe",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/hamu.jpg"), require("./assets/hamu.jpg")],
        },
        {
          id: 101,
          name: "Historic Main Street",
          city: "Kampala",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/Historic-Main-Street.jpg"), require("./assets/Historic-Main-Street.jpg")],
        },
        {
          id: 102,
          name: "Kasubi Muteesa I Royal Mosque",
          city: "Kampala",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/Kasubi-Muteesa-I-Royal-Mosque.jpg"), require("./assets/Kasubi-Muteesa-I-Royal-Mosque.jpg")],
        },
        {
          id: 103,
          name: "Kisingiri House",
          city: "Kampala",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/Kisingiri-House.jpg"), require("./assets/Kisingiri-House.jpg")],
        },
        {
          id: 104,
          name: "Kisosonkole House",
          city: "Kampala",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/Kisosonkole-House.jpg"), require("./assets/Kisosonkole-House.jpg")],
        },
        {
          id: 104,
          name: "Madhvani Building",
          city: "Kampala",
          description: "coming soon",
          location: { latitude: 0.6712, longitude: 30.2735 },
          images: [require("./assets/Madhvani-Building.jpg"), require("./assets/Madhvani-Building.jpg")],
        },
        {
          id: 105,
          name: "Ministry of Lands and Mapping Building",
          city: "Entebbe",
          description: "coming soon",
          location: { latitude: 0.0529, longitude: 32.4617 },
          images: [require("./assets/Land_building.jpg"), require("./assets/Land_building.jpg")],
        },
        {
          id: 107,
          name: "St Joseph Cathedral",
          city: "Kampala",
          description: "Coming soon",
          location: { latitude: 0.6696, longitude: 30.2791 },
          images: [require("./assets/st_joseph_cathedral.jpg"), require("./assets/st_joseph_cathedral.jpg")],
        },
        {
          id: 108,
          name: "Royal Mile",
          city: "Kampala",
          description: "Coming soon",
          location: { latitude: 0.6696, longitude: 30.2791 },
          images: [require("./assets/royal.jpg"), require("./assets/st_joseph_cathedral.jpg")],
        },
        {
          id: 109,
          name: "World-Wars' Memorial Monument",
          city: "Kampala",
          description: "Coming soon",
          location: { latitude: 0.6696, longitude: 30.2791 },
          images: [require("./assets/World-Wars'-Memorial-Monument.jpg"), require("./assets/st_joseph_cathedral.jpg")],
        },
        {
          id: 110,
          name: "Kabahango Palace",
          city: "Fort Portal",
          description: "Coming soon",
          location: { latitude: 0.6696, longitude: 30.2791 },
          images: [require("./assets/Kabahango.jpg"), require("./assets/Kabahangos.jpg")],
        },
]